Fatal error: exception Failure("Break cannot be called outside of a loop")
